export const GET_ERRORS = 'GET_ERRORS';
export const GET_RESPONSE = 'GET_RESPONSE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const EVENTS_LOADING = 'EVENTS_LOADING';
export const ORGANIZERS_LOADING = 'ORGANIZERS_LOADING';
export const SPONSORS_LOADING = 'SPONSORS_LOADING';
